name: Check Tennis Courts

on:
  schedule:
    - cron: '0 21 * * *' # 毎日定時に実行（必要に応じて調整してください）
  workflow_dispatch: # 手動実行ボタン用

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  check-courts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install
          npx playwright install chromium

      - name: Run script
        env:
          SPOREC_ID: ${{ secrets.SPOREC_ID }}
          SPOREC_PW: ${{ secrets.SPOREC_PW }}
          TOSHIMA_ID: ${{ secrets.TOSHIMA_ID }}
          TOSHIMA_PW: ${{ secrets.TOSHIMA_PW }}
          SUMIDA_ID: ${{ secrets.SUMIDA_ID }}
          SUMIDA_PW: ${{ secrets.SUMIDA_PW }}
          CHIYODA_ID: ${{ secrets.CHIYODA_ID }}
          CHIYODA_PW: ${{ secrets.CHIYODA_PW }}
        run: node src/checker.js
